DOC UPDATES: AS, VS and FSP A
scott-huberty/q1k-neuroimaging pull request #10
Opened 2023-10-22 23:59 UTC by gabrielblancogomez

Added new .rst files in the docs for Anti-Saccade, Visual Search and Face Social Preference. Also updated the index file. However, videos and images need to be updated for all these new tasks

2023-10-24 20:34 UTC, scott-huberty requested changes
Thanks @gabrielblancogomez, looks like it is nearly there!
 
I've suggested some changes. I've added the correct video and image links, and made some nitpicks on formatting.

Also a general comment: _never_ develop on or submit a pull request from your main branch. Always do `git checkout -b your_new_branch_name` and develop your new code on that branch.


You can only ever submit 1 pull request from any given branch - so now you will never be able to submit another pull request from your main branch (not that you'd want to). Second, There should be a one way flow of updates from `upstream/main` (i.e. `scott-huberty/q1k-neuroimaging/main`) to _your_ main branch. Not the other way around. Doing so could cause conflicts when you try to do  a `git pull upstream main` later.

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +.. vimeo:: 8741343
```suggestion
.. vimeo:: 877645510
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/face_social_preference.rst
> +.. vimeo:: 8741343
```suggestion
.. vimeo:: 877645530
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/face_social_preference.rst
> +.. figure:: https://raw.githubusercontent.com/scott-huberty/Q1K-doc-assets/main/_images/task_images/Q1K-FSP.png
```suggestion
.. figure:: https://raw.githubusercontent.com/scott-huberty/Q1K-doc-assets/main/_images/task_images/Q1K-Face-Social-Preference.png
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +The trial begins with the message ``DISPLAY_FIXATION``, followed by either ``GAZE_TO_FIX``
```suggestion
The trial begins with the message ``"DISPLAY_FIXATION"``, followed by either ``"GAZE_TO_FIX"``
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +The trial begins with the message ``DISPLAY_FIXATION``, followed by either ``GAZE_TO_FIX``
I'm putting quotes around these so that it is clear that these are strings and not variables.

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +or ``TRIAL_TIMEOUT``(if not gaze within ``2500ms``). When the distractor is shown.
```suggestion
or ``"TRIAL_TIMEOUT"``(if not gaze within ``2500ms``). When the distractor is shown. 
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +``ONSET_DISTRACTOR`` is written, if gaze looks directly at the distractor ``GAZE_TO_DISTRACTOR``
```suggestion
``"ONSET_DISTRACTOR"`` is written, if gaze looks directly at the distractor ``"GAZE_TO_DISTRACTOR"``
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +is written, or ``PREDICT_TARGET_GAZE`` if gaze goes directly to the target side. If
```suggestion
is written, or ``"PREDICT_TARGET_GAZE"`` if gaze goes directly to the target side. If
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +no gaze is to the target side, after ``200ms``, the message ``DISTRACTOR_OFFSET``
```suggestion
no gaze is to the target side, after ``200ms``, the message ``"DISTRACTOR_OFFSET"``
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +``GAZE_TO_DISTRACTOR`` is written.  If the IB trigger for the target side fires,
```suggestion
``"GAZE_TO_DISTRACTOR"`` is written.  If the IB trigger for the target side fires, 
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +``PREDICT_TARGET_GAZE`` is written. If no gaze is detected to the target side within
```suggestion
``"PREDICT_TARGET_GAZE"`` is written. If no gaze is detected to the target side within
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +``1000ms``, ``TARGET_ONSET`` is written when the red target image is displayed. If
```suggestion
``1000ms``, ``"TARGET_ONSET"`` is written when the red target image is displayed. If 
```

2023-10-24 20:34 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +``1000ms``, ``TARGET_ONSET`` is written when the red target image is displayed. If
Ditto for the other _string_ messages in this file and the other files.

2023-10-24 20:48 UTC, gabrielblancogomez commented on docs/source/tasks/anti_saccade.rst
> +``1000ms``, ``TARGET_ONSET`` is written when the red target image is displayed. If
Thanks @scott-huberty! I am still not super comfortable submitting pull requests on github (the upstream main vs new branch is not super clear) but I will keep it in mind. Maybe next time I develop some code and try to upload it we can do it together to make sure its all good.

2023-10-24 21:05 UTC, scott-huberty commented on docs/source/tasks/anti_saccade.rst
> +``1000ms``, ``TARGET_ONSET`` is written when the red target image is displayed. If
@gabrielblancogomez no problem, with things like `git`, you learn by doing 🙂

I'll follow up with some instructions to move these commits to a new branch, and rebase with upstream main (there will be conflicts from a recent PR of mine that touched the same lines of code as you have in this PR).

2023-11-22 14:46 UTC, closed without merging

2023-11-22 14:51 UTC, scott-huberty commented
Hey gabe here is what I need you to do:

```
cd to/q1k-neuroimaging/folder

git branch # make sure it says main

# create new branch which is a copy of the current state of the main branch
git checkout -b doc_udpates
```

Create a new pull request